### Basic math operations

In [1]:
4+5

9

In [3]:
3**4

81

In [4]:
91/2

45.5

### "Vectors"

In [13]:
# let's get numpy
import sys
!{sys.executable} -m pip install numpy

    100% |████████████████████████████████| 20.0MB 87kB/s  eta 0:00:01


In [23]:
import numpy as np

A = np.array([10, 20, 30])
display(type(A))
display(A.shape)
A

numpy.ndarray

(3,)

array([10, 20, 30])

In [24]:
# Python is 0-indexed
display(A[1])
A[0]

20

10

### "Matrix ops"

In [31]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
display(type(M))
display(M.shape)
M

numpy.ndarray

(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# transpose it
np.transpose(M)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
M[0,1] = 3663
M

array([[   1, 3663,    3],
       [   4,    5,    6],
       [   7,    8,    9]])

In [46]:
from numpy.linalg import inv

inv(M)

array([[-1.36574706e-04, -1.49972685e+00,  9.99863425e-01],
       [ 2.73149413e-04, -5.46298825e-04,  2.73149413e-04],
       [-1.36574706e-04,  1.16693982e+00, -6.66803241e-01]])

In [48]:
# Exception if it's not inversable
M[0,1] = 2
inv(M)

LinAlgError: Singular matrix

### Data frames

In [51]:
# let's get pandas
!{sys.executable} -m pip install pandas

    100% |████████████████████████████████| 10.4MB 158kB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/0e/46/ae6773894f7eacf53308086287897ec568eac9768918d913d5b9d366c5db/numpy-1.17.3-cp36-cp36m-manylinux1_x86_64.whl
    100% |████████████████████████████████| 512kB 2.8MB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl


In [55]:
import pandas as pd
df = pd.read_csv("train.csv")
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [63]:
# tuple of (num_rows, nu m_columns)
df.shape

(614, 13)

In [65]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [67]:
# df.head() - defaults to 5
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [70]:
df.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [71]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [73]:
df['LoanAmount']

0        NaN
1      128.0
2       66.0
3      120.0
4      141.0
       ...  
609     71.0
610     40.0
611    253.0
612    187.0
613    133.0
Name: LoanAmount, Length: 614, dtype: float64

In [74]:
df.describe(df['LoanAmount'])

ValueError: percentiles should all be in the interval [0, 1]. Try [ nan 1.28 0.66 1.2  1.41 2.67 0.95 1.58 1.68 3.49 0.7  1.09 2.   1.14
 0.17 1.25 1.   0.76 1.33 1.15 1.04 3.15 1.16 1.12 1.51 1.91 1.22 1.1
 0.35 1.2  2.01 0.74 1.06 1.14 3.2   nan 1.   1.44 1.84 1.1  0.8  0.47
 0.75 1.34 0.96 0.88 0.44 1.44 1.2  1.44 1.   1.2  1.12 1.34 2.86 0.97
 0.96 1.35 1.8  1.44 1.2  0.99 1.65  nan 1.16 2.58 1.26 3.12 1.25 1.36
 1.72 0.97 0.81 0.95 1.87 1.13 1.76 1.1  1.8  1.3  1.11  nan 1.67 2.65
 0.5  1.36 0.99 1.04 2.1  1.75 1.31 1.88 0.81 1.22 0.25  nan 1.37 0.5
 1.15 1.31 1.33 1.51  nan  nan 1.6  1.   2.25 1.2  2.16 0.94 1.36 1.39
 1.52  nan 1.18 1.85 1.54 0.85 1.75 2.59 1.8  0.44 1.37 0.81 1.94 0.93
 3.7   nan 1.6  1.82 6.5  0.74 0.7  0.25 1.02 2.9  0.84 0.88 2.42 1.29
 1.85 1.68 1.75 1.22 1.87 1.   0.7  0.3  2.25 1.25 1.18 1.52 2.44 1.13
 0.5  6.   1.6  1.87 1.2  2.55 0.98 2.75 1.21 1.58 0.75 1.82 1.12 1.29
 0.63 2.   0.95 7.   0.81 1.87 0.87 1.16 1.01 4.95 1.16 1.02 1.8  0.67
 0.73 2.6  1.08 1.2  0.66 0.58 1.68 1.88 0.48 1.64 1.6  0.76 1.2  1.7
 1.87 1.2  1.13 0.83 0.9  1.66  nan 1.35 1.24 1.2  0.8  0.55 0.59 1.27
 2.14 1.28 2.4  1.3  1.37 1.   1.35 1.31 0.72 1.27 0.6  1.16 1.44 1.75
 1.28 1.7  1.38 2.1  1.58 2.   1.04 0.42 1.2  2.8  1.4  1.7  2.55 1.22
 1.12 0.96 1.2  1.4  1.55 1.08 1.23 1.2  1.12 1.37 1.23 0.9  2.01 1.38
 1.04 2.79 1.92 2.55 1.15 0.94 3.04 1.28 3.3  1.34 1.55 1.2  1.28 1.51
 1.5  1.6  1.35 0.9  0.3  1.36 1.26 1.5  0.9  1.15 2.07 0.8  4.36 1.24
 1.58 1.12 0.78 0.54  nan 0.89 0.99 1.2  1.15 1.87 1.39 1.27 1.34 1.43
 1.72 1.1  2.   1.35 1.51 1.13 0.93 1.05 1.32 0.96 1.4   nan 1.35 1.04
 4.8  1.85 0.84 1.11 0.56 1.44 1.59 1.11 1.2  0.88 1.12 1.55 1.15 1.24
  nan 1.32 3.   3.76 1.3  1.84 1.1  0.67 1.17 0.98 0.71 4.9  1.82 0.7
 1.6  1.76  nan 0.71 1.73 0.46 1.58 0.74 1.25 1.6  1.52 1.26 2.59 1.87
 2.28 3.08 0.95 1.05 1.3  1.16 1.65 0.67 1.   2.   0.81 2.36 1.3  0.95
 1.41 1.33 0.96 1.24 1.75 5.7  0.55 1.55 3.8  1.11 1.1  1.2  1.3  1.3
 0.71 1.3  1.28 2.96 1.56 1.28 1.   1.13 1.32  nan 1.36 1.25 1.85 2.75
 1.2  1.13 1.13 1.35 0.71 0.95 1.09 1.03 0.45 0.65 1.03 0.53 1.94 1.15
 1.15 0.66 1.52 3.6  0.62 1.6  2.18 1.1  1.78 0.6  1.6  2.39 1.12 1.38
 1.38 0.8  1.   1.1  0.96 1.21 0.81 1.33 0.87 0.6  1.5  1.05 4.05 1.43
 1.    nan 0.5   nan 1.87 1.38 1.87 1.8  1.48 1.52 1.75 1.3  1.1  0.55
 1.5  1.9  1.25 0.6  1.49 0.9  0.84 0.96 1.18 1.73 1.36 1.6  1.6  1.28
 1.53 1.32 0.98 1.4  0.7  1.1  0.98 1.1  1.62 1.13 1.   0.93 1.62 1.5
 2.3  1.32 0.86  nan 1.54 1.13 1.28 2.34 2.46 1.31 0.8  5.   1.6  0.75
 0.96 1.86 1.1  2.25 1.19 1.05 1.07 1.11 0.95 2.09 1.13 1.   2.08 1.38
 1.24 2.43 4.8  0.96 1.88 0.4  1.   2.5  1.48 0.7  3.11 1.5  1.13 1.23
 1.85 0.95 0.45 0.55 1.   4.8   nan 4.   1.1  1.61 0.94 1.3  2.16 1.
 1.1  1.96 1.25 1.26 3.24 1.07 0.66 1.57 1.4  0.99 0.95 1.28 1.02 1.55
 0.8  1.45 1.03 1.1   nan  nan 1.58 1.81 1.32 0.26 0.84 2.6  1.62 1.82
 1.08 6.   2.11 1.32 2.58 1.2  0.7  1.23 0.09 1.04 1.86 1.65 2.75 1.87
 1.5  1.08 1.36 1.1  1.07 1.61 2.05 0.9  0.36 0.61 1.46 1.72 1.04 0.7
 0.94 1.06 0.56 2.05 2.92 1.42 2.6  1.1  1.87 0.88 1.8  1.92 3.5  1.55
 1.28 1.72 4.96  nan 1.73 1.57 1.08 0.71 0.4  2.53 1.87 1.33] instead.